name: CD Hangman Front

on:
  workflow_dispatch: # Disparador manual

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Iniciar sesión en el Container Registry de GitHub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Crear una nueva imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/hangman-front:latest .start-code/hangman-front

      # Publicar la imagen en el Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/hangman-front:latest
