name: E2E Tests

on:
  workflow_dispatch: # Disparador manual

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js para Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Paso 3: Construir y ejecutar los contenedores necesarios
      - name: Build and Start API and Front containers
        run: |
          # Construir la imagen de la API
          docker build -t hangman-api .start-code/hangman-api
          # Construir la imagen del Frontend
          docker build -t hangman-front .start-code/hangman-front
          # Iniciar los contenedores
          docker run -d -p 3001:3000 hangman-api
          docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 hangman-front

      # Paso 4: Instalar dependencias para los tests e2e
      - name: Install e2e dependencies
        run: |
          cd .start-code/hangman-e2e/e2e
          npm install

      # Paso 5: Ejecutar los tests e2e con Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: .start-code/hangman-e2e/e2e
          start: npm test
          wait-on: http://localhost:8080
